import Navbar from "@/components/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-screen h-screen  flex flex-col ">
      <div className="flex flex-col ">
        <div className="bg-white py-4 border-b ">
          <div className="mx-auto container">
            <Navbar />
          </div>
        </div>
        <div className="mx-auto container py-4">{children}</div>
      </div>
    </div>
  );
}
